name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      # Runs a single command using the runners shell
      - name: Install Dependencies
        run: npm install
        
      # Runs a single command using the runners shell
      - name: Build for release
        run: npm run build
      
      - name: List output files
        run: ls

      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ftp://ftp.amusedtodeath.eu/prepatch/
          ftp-username: amusedtodeath.eu
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist